apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webapp-k8s-deployment
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: houssemdocker/webappfork8s:v2
        ports:
        - containerPort: 80
        
