apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webapp-k8s-deployment
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: houssemdocker/webappfork8s:v10
        ports:
        - containerPort: 80
        #added by me
        env :
          - name: DbConnectionString
            value: Server=mssql;Database=ProductsDB;User=sa;Password=@Aa123456;
            #value: Server=192.168.99.100,32714;Database=ProductsDB;User=sa;Password=@Aa123456; // works
            #value: mssql #mssql-service #mssql #"DbConnectionString value here ohooo"
        
        
